export const GET_DATABASE = 'GET_DATABASE';
export const SET_DATABASE = 'SET_DATABASE';
export const UPDATE_DATABASE = 'UPDATE_DATABASE';
export const DELETE_DATABASE = 'DELETE_DATABASE';
export const DATABASE_CHANGE_FIELD ='DATABASE_CHANGE_FIELD';