import type { ChatItem, ChatMessage } from '@/types/chatTypes'

const chats: ChatItem[] = [
    {
        id: 1,
        teacher: {
            id: 101,
            username: 'apetrova',
            firstName: 'Анна',
            lastName: 'Петрова',
            role: 'teacher',
            position: 'Преподаватель',
            isOnline: true,
        },
        context: {
            courseId: 21,
            courseTitle: 'Оператор SELECT (версия 2021)',
            taskId: 12,
            taskNumber: 12,
            taskTitle: 'Задача #12',
            topicTitle: 'Фильтрация данных',
        },
        title: 'Оператор SELECT (версия 2021) / Задача #12',
        lastMessage: 'Попробуйте использовать WHERE вместо HAVING...',
        lastMessageAt: '10:34',
        unreadCount: 0,
        category: 'task',
        messages: [
            {
                id: 1,
                chatId: 1,
                authorId: 'student',
                authorRole: 'student',
                authorName: 'Вы',
                content: 'Здравствуйте. Не могу понять, почему мой запрос не проходит проверку. Я использовал COUNT, как в предыдущих задачах.',
                timestamp: '14:28',
                isOwn: true,
            },
            {
                id: 2,
                chatId: 1,
                authorId: 101,
                authorRole: 'teacher',
                authorName: 'Анна Петрова',
                content: 'Добрый день. В этой задаче нужно выбрать все товары дороже 1000, а не считать их количество. COUNT используется для подсчета, а здесь нужен просто вывод строк.',
                timestamp: '14:30',
                isOwn: false,
            },
            {
                id: 3,
                chatId: 1,
                authorId: 101,
                authorRole: 'teacher',
                authorName: 'Анна Петрова',
                content: 'Попробуйте такой запрос:\n\n```sql\nSELECT *\nFROM products\nWHERE price > 1000;\n```',
                timestamp: '14:32',
                isOwn: false,
            },
            {
                id: 4,
                chatId: 1,
                authorId: 'student',
                authorRole: 'student',
                authorName: 'Вы',
                content: 'Спасибо. Теперь понятно. Попробую еще раз.',
                timestamp: '14:35',
                isOwn: true,
            },
        ],
    },
    {
        id: 2,
        teacher: {
            id: 102,
            username: 'msokolov',
            firstName: 'Михаил',
            lastName: 'Соколов',
            role: 'teacher',
            position: 'Преподаватель',
        },
        context: {
            courseId: 22,
            courseTitle: 'JOIN и связи между таблицами',
            topicTitle: 'JOIN и связи между таблицами',
        },
        title: 'JOIN и связи между таблицами',
        lastMessage: 'Отличный вопрос про LEFT JOIN.',
        lastMessageAt: 'вчера',
        unreadCount: 2,
        category: 'course',
        messages: [
            {
                id: 5,
                chatId: 2,
                authorId: 102,
                authorRole: 'teacher',
                authorName: 'Михаил Соколов',
                content: 'Отличный вопрос про LEFT JOIN. Разберем его на следующем занятии.',
                timestamp: '16:40',
                isOwn: false,
            },
        ],
    },
    {
        id: 3,
        teacher: {
            id: 103,
            username: 'evolkova',
            firstName: 'Елена',
            lastName: 'Волкова',
            role: 'teacher',
            position: 'Преподаватель',
        },
        context: {
            courseId: 23,
            courseTitle: 'Агрегатные функции',
            taskId: 8,
            taskNumber: 8,
            taskTitle: 'Задача #8',
            topicTitle: 'Агрегатные функции',
        },
        title: 'Агрегатные функции / Задача #8',
        lastMessage: 'Проверьте решение. Жду вашего ответа, для то...',
        lastMessageAt: '2 дня назад',
        unreadCount: 0,
        category: 'task',
        isWaiting: true,
        messages: [],
    },
    {
        id: 4,
        teacher: {
            id: 104,
            username: 'dkovalev',
            firstName: 'Дмитрий',
            lastName: 'Ковалев',
            role: 'teacher',
            position: 'Преподаватель',
        },
        context: {
            courseId: 24,
            courseTitle: 'Подзапросы и вложенные SELECT',
            topicTitle: 'Подзапросы и вложенные SELECT',
        },
        title: 'Подзапросы и вложенные SELECT',
        lastMessage: 'Разберем подробнее на следующем занятии.',
        lastMessageAt: '3 дня назад',
        unreadCount: 0,
        category: 'course',
        messages: [],
    },
]

export const chatMockService = {
    async getChats(): Promise<ChatItem[]> {
        return structuredClone(chats)
    },

    async sendMockMessage(chatId: number | string, content: string): Promise<ChatMessage> {
        return {
            id: `${chatId}-${Date.now()}`,
            chatId,
            authorId: 'student',
            authorRole: 'student',
            authorName: 'Вы',
            content,
            timestamp: new Intl.DateTimeFormat('ru-RU', {
                hour: '2-digit',
                minute: '2-digit',
            }).format(new Date()),
            isOwn: true,
        }
    },
}
