export const SECTIONS = 'SECTIONS';
export const THEMES = 'THEMES';
export const CURRENT_TOPICS = 'CURRENT_TOPICS';
export const GET_SECTIONS_FETCHING = 'GET_SECTIONS_FETCHING';
export const GET_THEMES_FETCHING = 'GET_THEMES_FETCHING';
export const CREATE_TOPIC_FETCHING = 'CREATE_TOPIC_FETCHING';

export const SECTION_FIELD = 'SECTION_FIELD';
export const NUMBER_FIELD = 'NUMBER_FIELD';
export const NAME_FIELD = 'NAME_FIELD';
export const CONTENT_FIELD = 'CONTENT_FIELD';
export const THEMES_FIELD = 'THEMES_FIELD';