export const TOPICS = 'TOPICS';
export const GET_TOPICS_FETCHING = 'GET_TOPICS_FETCHING';
export const CURRENT_TOPICS = 'CURRENT_TOPICS';
export const GET_CURRENT_TOPICS_FETCHING = 'GET_CURRENT_TOPICS_FETCHING';
export const DELETE_TOPICS_FETCHING = 'DELETE_TOPICS_FETCHING';