/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg-main)',
        'bg-header': 'var(--bg-header)',
        'segment-begin': 'var(--segment-begin)',
        'segment-end': 'var(--segment-end)',
        page: 'var(--color-page)',
        header: 'var(--color-header)',
        'header-text': 'var(--color-header-text)',
        footer: 'var(--color-footer)',
        panel: 'var(--color-panel)',
        'panel-strong': 'var(--color-panel-strong)',
        'editor-card': 'var(--color-editor-card)',
        'result-header': 'var(--color-result-header)',
        card: 'var(--color-card)',
        'card-muted': 'var(--color-card-muted)',
        'app-text': 'var(--color-text)',
        'app-muted': 'var(--color-text-muted)',
        'app-border': 'var(--color-border)',
        'app-border-soft': 'var(--color-border-soft)',
        'primary-action': 'var(--color-primary)',
        'primary-action-hover': 'var(--color-primary-hover)',
        'primary-gradient-start': 'var(--color-primary-gradient-start)',
        'primary-gradient-end': 'var(--color-primary-gradient-end)',
        'success-action': 'var(--color-success)',
        'progress-track': 'var(--color-progress-track)',
        'progress-green': 'var(--color-progress-green)',
        'icon-box': 'var(--color-icon-box)',
        'surface-contrast': 'var(--color-surface-contrast)',
        'sql-pink': 'var(--color-sql-pink)',
        'status-success-bg': 'var(--color-status-success-bg)',
        'status-success-text': 'var(--color-status-success-text)',
        'status-progress-bg': 'var(--color-status-progress-bg)',
        'status-progress-text': 'var(--color-status-progress-text)',
        'auth-surface': 'var(--color-auth-surface)',
        'auth-surface-muted': 'var(--color-auth-surface-muted)',
        'auth-table': 'var(--color-auth-table)',
        'auth-input': 'var(--color-auth-input)',
        'auth-input-alt': 'var(--color-auth-input-alt)',
        'auth-border': 'var(--color-auth-border)',
        'auth-type-muted': 'var(--color-auth-type-muted)',
        'auth-type-muted-register': 'var(--color-auth-type-muted-register)',
        'auth-prompt': 'var(--color-auth-prompt)',
        'auth-checkbox': 'var(--color-auth-checkbox)',
        'auth-checkbox-bg': 'var(--color-auth-checkbox-bg)',
        'auth-checkbox-mark': 'var(--color-auth-checkbox-mark)',
        'auth-checkbox-border': 'var(--color-auth-checkbox-border)',
        course: {
          'card-begin': 'var(--cc-begin)',
          'card-end': 'var(--cc-end)',
          'grid': 'var(--course-grid)',
          'grid-stroke': 'var(--course-stroke)',
        },
        text: {
          main: 'var(--text-main)',
          neg: 'var(--text-neg)',
        },
        primary: {
          50: '#EAF0FF',
          100: '#D9E4FF',
          200: '#B7CBFF',
          500: 'var(--color-primary)',
          600: 'var(--color-primary-hover)',
          700: '#1437C2',
        },
        success: {
          begin: 'var(--success-begin)',
          end: 'var(--success-end)',
        },
        danger: 'var(--danger)',
      },
      boxShadow: {
        card: '0 10px 30px rgba(15, 23, 42, 0.08)',
      },
      backgroundImage: {
        'primary-gradient': 'var(--gradient-primary)',
        'panel-gradient': 'var(--gradient-panel)',
        'card-surface-gradient': 'var(--gradient-card-surface)',
        'card-surface-horizontal-gradient': 'var(--gradient-card-surface-horizontal)',
        'inner-panel-gradient': 'var(--gradient-inner-panel)',
        'result-header-gradient': 'var(--gradient-result-header)',
        'auth-surface-gradient': 'var(--gradient-auth-surface)',
        'auth-header-gradient': 'var(--gradient-auth-header)',
        'auth-button-gradient': 'var(--gradient-auth-button)',
        'auth-info-header-gradient': 'var(--gradient-auth-info-header)',
        'auth-info-surface-gradient': 'var(--gradient-auth-info-surface)',
      },
      fontFamily: {
        mono: ['JetBrains Mono NL', 'monospace'],
      },
    },
  },
  plugins: [],
}
