/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg-main)',
        'bg-header': 'var(--bg-header)',
        'segment-begin': 'var(--segment-begin)',
        'segment-end': 'var(--segment-end)',
        page: 'var(--color-page)',
        header: 'var(--color-header)',
        'header-text': 'var(--color-header-text)',
        footer: 'var(--color-footer)',
        panel: 'var(--color-panel)',
        'panel-strong': 'var(--color-panel-strong)',
        'editor-card': 'var(--color-editor-card)',
        'result-header': 'var(--color-result-header)',
        card: 'var(--color-card)',
        'card-muted': 'var(--color-card-muted)',
        'app-text': 'var(--color-text)',
        'app-muted': 'var(--color-text-muted)',
        'app-border': 'var(--color-border)',
        'app-border-soft': 'var(--color-border-soft)',
        'primary-action': 'var(--color-primary)',
        'primary-action-hover': 'var(--color-primary-hover)',
        'primary-gradient-start': 'var(--color-primary-gradient-start)',
        'primary-gradient-end': 'var(--color-primary-gradient-end)',
        'success-action': 'var(--color-success)',
        'progress-track': 'var(--color-progress-track)',
        'progress-green': 'var(--color-progress-green)',
        'icon-box': 'var(--color-icon-box)',
        'surface-contrast': 'var(--color-surface-contrast)',
        'sql-pink': 'var(--color-sql-pink)',
        'status-success-bg': 'var(--color-status-success-bg)',
        'status-success-text': 'var(--color-status-success-text)',
        'status-progress-bg': 'var(--color-status-progress-bg)',
        'status-progress-text': 'var(--color-status-progress-text)',
        'auth-surface': 'var(--color-auth-surface)',
        'auth-surface-muted': 'var(--color-auth-surface-muted)',
        'auth-table': 'var(--color-auth-table)',
        'auth-input': 'var(--color-auth-input)',
        'auth-input-alt': 'var(--color-auth-input-alt)',
        'auth-border': 'var(--color-auth-border)',
        'auth-type-muted': 'var(--color-auth-type-muted)',
        'auth-type-muted-register': 'var(--color-auth-type-muted-register)',
        'auth-prompt': 'var(--color-auth-prompt)',
        'auth-checkbox': 'var(--color-auth-checkbox)',
        'auth-checkbox-bg': 'var(--color-auth-checkbox-bg)',
        'auth-checkbox-mark': 'var(--color-auth-checkbox-mark)',
        'auth-checkbox-border': 'var(--color-auth-checkbox-border)',
        'auth-separator': 'var(--color-auth-separator)',
        'auth-social-button': 'var(--color-auth-social-button)',
        'auth-social-button-border': 'var(--color-auth-social-button-border)',
        'auth-social-button-text': 'var(--color-auth-social-button-text)',
        'profile-logout-bg': 'var(--color-profile-logout-bg)',
        'profile-logout-text': 'var(--color-profile-logout-text)',
        'profile-details-surface': 'var(--color-profile-details-surface)',
        'profile-prompt': 'var(--color-profile-prompt)',
        'profile-stat-blue-bg': 'var(--color-profile-stat-blue-bg)',
        'profile-stat-blue-text': 'var(--color-profile-stat-blue-text)',
        'profile-stat-green-bg': 'var(--color-profile-stat-green-bg)',
        'profile-stat-green-text': 'var(--color-profile-stat-green-text)',
        'profile-stat-purple-bg': 'var(--color-profile-stat-purple-bg)',
        'profile-stat-purple-text': 'var(--color-profile-stat-purple-text)',
        'profile-stat-orange-bg': 'var(--color-profile-stat-orange-bg)',
        'profile-stat-orange-text': 'var(--color-profile-stat-orange-text)',
        'chat-page': 'var(--color-chat-page)',
        'chat-panel': 'var(--color-chat-panel)',
        'chat-surface': 'var(--color-chat-surface)',
        'chat-surface-active': 'var(--color-chat-surface-active)',
        'chat-border': 'var(--color-chat-border)',
        'chat-border-strong': 'var(--color-chat-border-strong)',
        'chat-border-active': 'var(--color-chat-border-active)',
        'chat-text': 'var(--color-chat-text)',
        'chat-muted': 'var(--color-chat-muted)',
        'chat-placeholder': 'var(--color-chat-placeholder)',
        'chat-avatar': 'var(--color-chat-avatar)',
        'chat-on-accent': 'var(--color-chat-on-accent)',
        'chat-filter-active-bg': 'var(--color-chat-filter-active-bg)',
        'chat-filter-active-text': 'var(--color-chat-filter-active-text)',
        'chat-action-button': 'var(--color-chat-action-button)',
        'chat-online': 'var(--color-chat-online)',
        'chat-send': 'var(--color-chat-send)',
        'chat-warning': 'var(--color-chat-warning)',
        'chat-code-bg': 'var(--color-chat-code-bg)',
        'chat-code-text': 'var(--color-chat-code-text)',
        'chat-own-message': 'var(--color-chat-own-message)',
        'chat-incoming-message': 'var(--color-chat-incoming-message)',
        'chat-composer-input': 'var(--color-chat-composer-input)',
        'chat-icon-button': 'var(--color-chat-icon-button)',
        course: {
          'card-begin': 'var(--cc-begin)',
          'card-end': 'var(--cc-end)',
          'grid': 'var(--course-grid)',
          'grid-stroke': 'var(--course-stroke)',
        },
        link: {
          default: 'var(--link-default)',
          hover: 'var(--link-hover)',
        },
        task: {
          begin: 'var(--task-begin)',
          end: 'var(--task-end)',
          hard: 'var(--hard)',
          medium: 'var(--medium)',
          easy: 'var(--easy)',
          neutral: 'var(--neutral)',
        },
        sidebar: {
          bg: 'var(--sidebar-bg)',
          elem: 'var(--sidebar-elem)',
        },
        editor: {
          begin: 'var(--editor-begin)',
          end: 'var(--editor-end)',
        },
        schema: {
          'bg-begin': 'var(--schema-bg-begin)',
          'bg-end': 'var(--schema-bg-end)',
          grid: 'var(--schema-grid)',
          header: 'var(--schema-header)'
        },
        text: {
          main: 'var(--text-main)',
          neg: 'var(--text-neg)',
          secondary: 'var(--text-secondary)',
        },
        primary: {
          begin: 'var(--primary-begin)',
          end: 'var(--primary-end)',
          50: '#EAF0FF',
          100: '#D9E4FF',
          200: '#B7CBFF',
          500: 'var(--color-primary)',
          600: 'var(--color-primary-hover)',
          700: '#1437C2',
        },
        success: {
          base: 'var(--success)',
          begin: 'var(--success-begin)',
          end: 'var(--success-end)',
        },
        secondary: 'var(--secondary)',
        danger: 'var(--danger)',
      },
      boxShadow: {
        card: '0 10px 30px rgba(15, 23, 42, 0.08)',
      },
      backgroundImage: {
        'primary-gradient': 'var(--gradient-primary)',
        'panel-gradient': 'var(--gradient-panel)',
        'card-surface-gradient': 'var(--gradient-card-surface)',
        'card-surface-horizontal-gradient': 'var(--gradient-card-surface-horizontal)',
        'inner-panel-gradient': 'var(--gradient-inner-panel)',
        'result-header-gradient': 'var(--gradient-result-header)',
        'auth-surface-gradient': 'var(--gradient-auth-surface)',
        'auth-header-gradient': 'var(--gradient-auth-header)',
        'auth-button-gradient': 'var(--gradient-auth-button)',
        'auth-info-header-gradient': 'var(--gradient-auth-info-header)',
        'auth-info-surface-gradient': 'var(--gradient-auth-info-surface)',
        'profile-card-gradient': 'var(--gradient-profile-card)',
        'profile-avatar-gradient': 'var(--gradient-profile-avatar)',
        'chat-header-gradient': 'var(--gradient-chat-header)',
      },
      fontFamily: {
        mono: ['JetBrains Mono NL', 'monospace'],
      },
    },
  },
  plugins: [],
}
