export const CREATE_TASK = 'CREATE_TASK';
export const TASK_CHANGE_FIELD ='TASK_CHANGE_FIELD';
export const GET_THEMES = 'GET_THEMES_FIELD';
export const SET_THEMES = 'SET_THEMES_FIELD';
export const GET_DATABASES = 'GET_DATABASES_FIELD';
export const SET_DATABASES = 'SET_DATABASES_FIELD';