export const GET_DATABASES = 'GET_DATABASES';
export const GET_CURRENT_DATABASES = 'GET_CURRENT_DATABASES';
export const SET_CURRENT_DATABASES = 'SET_CURRENT_DATABASES';
export const SET_DATABASES = 'SET_DATABASES';
export const SET_DATABASES_COUNT = 'SET_DATABASES_COUNT';
export const DELETE_DATABASE = 'DELETE_DATABASE';