export const DATABASES = 'DATABASES';
export const GET_DATABASES_FETCHING = 'GET_DATABASES_FETCHING';
export const CURRENT_DATABASES = 'CURRENT_DATABASES';
export const GET_CURRENT_DATABASES_FETCHING = 'GET_CURRENT_DATABASES_FETCHING';
export const DELETE_DATABASE_FETCHING = 'DELETE_DATABASE_FETCHING';